server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Sirve activos estáticos normalmente
  location /assets/ {
    try_files $uri =404;
  }

  # Fallback SPA (React Router/Vite)
  location / {
    try_files $uri $uri/ /index.html;
  }
}