# fly.toml app configuration file generated for scouts-frontend on 2025-10-09T17:08:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scouts-backend'
primary_region = 'gru'

[http_service]
internal_port = 8080
# force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

    [[http_service.checks]]
    type = "http"
    method = "GET"
    path = "/api/v1/test/health"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"

[[vm]]
    memory = '1gb'
    cpu_kind = 'shared'
    cpus = 1

# Variables de entorno no sensibles
[env]
    SERVER_PORT = "8080"
    APP_PROFILE = "production"
    SHOW_SQL = "false"
    HIBERNATE_DDL_AUTO = "validate"
    LIQUIBASE_ENABLED = "false"
    OKTA_OAUTH2_ISSUER = "https://dev-peshzy4g14jvfyku.us.auth0.com/"
    OKTA_OAUTH2_AUDIENCE = "https://scouts-platform-backend/"
    AUTH0_CLIENT_ID="OiWaUylWieF26UdxNdISP7LtZiIwANR8"
    AUTH0_DOMAIN = "dev-peshzy4g14jvfyku.us.auth0.com"
    AUTH0_AUDIENCE = "https://dev-peshzy4g14jvfyku.us.auth0.com/api/v2/"
    DB_URL = "jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres"
    DB_USER = "api_user.mirhzylkikwpydtwelvj"

[build]
    dockerfile = "Dockerfile"
    context = "."