# fly.toml app configuration file generated for scouts-frontend on 2025-10-09T17:08:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scouts-backend'
primary_region = 'gru'

[http_service]
internal_port = 8080
# force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

    [[http_service.checks]]
    type = "http"
    method = "GET"
    path = "/api/v1/test/health"
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"

[[vm]]
    memory = '1gb'
    cpu_kind = 'shared'
    cpus = 1

# Variables de entorno no sensibles
[env]
    SPRING_DATASOURCE_PASSWORD = "u52HpYJfyWTSheL5tgHnb9ySDcqFga"

[build]
    dockerfile = "Dockerfile"
    context = "."