package uao.edu.co.scouts_project.organigrama.repository;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import uao.edu.co.scouts_project.organigrama.model.Group;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@ActiveProfiles("test")
@DataJpaTest(properties = "spring.jpa.hibernate.ddl-auto=none")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class GroupRepositoryTest {

    @Configuration
    @EnableJpaRepositories(basePackageClasses = GroupRepository.class)
    @EntityScan(basePackageClasses = Group.class)
    static class JpaSliceConfig { }

    @Autowired
    private GroupRepository groupRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeAll
    void createSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS groups");
        jdbcTemplate.execute("""
            CREATE TABLE groups (
                group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id VARCHAR(255) NOT NULL,
                slug VARCHAR(255) NOT NULL,
                name VARCHAR(255) NOT NULL,
                district VARCHAR(255),
                identifier_number VARCHAR(255),
                address VARCHAR(255),
                phone VARCHAR(255),
                email VARCHAR(255),
                founded_in DATE,
                motto VARCHAR(255),
                mission VARCHAR(2048),
                vision VARCHAR(2048),
                history VARCHAR(4096),
                logo_object_id UUID,
                scarf_object_id UUID,
                social_links VARCHAR(10000),
                config VARCHAR(10000),
                is_active BOOLEAN,
                created_at TIMESTAMP,
                updated_at TIMESTAMP,
                status VARCHAR(64)
            )
        """);
    }

    @BeforeEach
    void cleanTable() {
        jdbcTemplate.execute("DELETE FROM groups");
    }

    // ---------- helpers ----------
    private Group make(String tenantId, String slug, String name) {
        Group g = new Group(tenantId, slug, name);
        g.setDistrict("Distrito Valle");
        g.setIdentifierNumber(null);
        g.setFoundedIn(LocalDate.of(1998, 1, 1));
        g.setIsActive(true);              // <- CAMBIO: antes g.setActive(true)
        g.setStatus("ACTIVE");
        return g;
    }

    // ---------- existsByTenantIdAndSlug ----------
    @Test
    @DisplayName("existsByTenantIdAndSlug → true cuando existe")
    void existsByTenantIdAndSlug_true() {
        groupRepository.save(make("tenant1", "centinelas-113", "Grupo Centinelas"));
        boolean out = groupRepository.existsByTenantIdAndSlug("tenant1", "centinelas-113");
        assertThat(out).isTrue();
    }

    @Test
    @DisplayName("existsByTenantIdAndSlug → false cuando NO existe")
    void existsByTenantIdAndSlug_false() {
        groupRepository.save(make("tenant1", "centinelas-113", "Grupo Centinelas"));
        boolean out = groupRepository.existsByTenantIdAndSlug("tenant1", "otro-slug");
        assertThat(out).isFalse();
    }

    // ---------- existsByTenantIdAndIdentifierNumber ----------
    @Test
    @DisplayName("existsByTenantIdAndIdentifierNumber → true cuando coincide")
    void existsByTenantIdAndIdentifierNumber_true() {
        Group g = make("tenant1", "g1", "G1");
        g.setIdentifierNumber("ID-803");
        groupRepository.save(g);

        boolean out = groupRepository.existsByTenantIdAndIdentifierNumber("tenant1", "ID-803");
        assertThat(out).isTrue();
    }

    @Test
    @DisplayName("existsByTenantIdAndIdentifierNumber → false cuando no coincide")
    void existsByTenantIdAndIdentifierNumber_false() {
        Group g = make("tenant1", "g1", "G1");
        g.setIdentifierNumber("ID-803");
        groupRepository.save(g);

        boolean out = groupRepository.existsByTenantIdAndIdentifierNumber("tenant1", "ID-999");
        assertThat(out).isFalse();
    }

    // ---------- findByTenantId ----------
    @Test
    @DisplayName("findByTenantId → devuelve solo del tenant pedido")
    void findByTenantId_returnsList() {
        groupRepository.save(make("tenant1", "g1", "G1"));
        groupRepository.save(make("tenant1", "g2", "G2"));
        groupRepository.save(make("tenant2", "g3", "G3"));

        List<Group> out = groupRepository.findByTenantId("tenant1");
        assertThat(out).extracting(Group::getSlug).containsExactlyInAnyOrder("g1", "g2");
    }

    @Test
    @DisplayName("findByTenantId → lista vacía cuando no hay datos")
    void findByTenantId_empty() {
        List<Group> out = groupRepository.findByTenantId("tenantX");
        assertThat(out).isEmpty();
    }

    // ---------- findByTenantIdAndIsActive ----------
    @Test
    @DisplayName("findByTenantIdAndIsActive → filtra por activo=true")
    void findByTenantIdAndIsActive_true() {
        Group a = make("tenant1", "g1", "G1"); a.setIsActive(true);   // <- CAMBIO
        Group b = make("tenant1", "g2", "G2"); b.setIsActive(false);  // <- CAMBIO
        Group c = make("tenant1", "g3", "G3"); c.setIsActive(true);   // <- CAMBIO
        groupRepository.saveAll(List.of(a,b,c));

        List<Group> out = groupRepository.findByTenantIdAndIsActive("tenant1", true);
        assertThat(out).extracting(Group::getSlug).containsExactlyInAnyOrder("g1", "g3");
    }

    @Test
    @DisplayName("findByTenantIdAndIsActive → filtra por activo=false")
    void findByTenantIdAndIsActive_false() {
        Group a = make("tenant1", "g1", "G1"); a.setIsActive(true);   // <- CAMBIO
        Group b = make("tenant1", "g2", "G2"); b.setIsActive(false);  // <- CAMBIO
        groupRepository.saveAll(List.of(a,b));

        List<Group> out = groupRepository.findByTenantIdAndIsActive("tenant1", false);
        assertThat(out).extracting(Group::getSlug).containsExactlyInAnyOrder("g2");
    }

    // ---------- findByTenantIdAndSlug ----------
    @Test
    @DisplayName("findByTenantIdAndSlug → encuentra el grupo")
    void findByTenantIdAndSlug_found() {
        groupRepository.save(make("tenant1", "g1", "G1"));
        Optional<Group> out = groupRepository.findByTenantIdAndSlug("tenant1", "g1");
        assertThat(out).isPresent();
        assertThat(out.get().getName()).isEqualTo("G1");
    }

    @Test
    @DisplayName("findByTenantIdAndSlug → vacío si no coincide")
    void findByTenantIdAndSlug_empty() {
        groupRepository.save(make("tenant1", "g1", "G1"));
        Optional<Group> out = groupRepository.findByTenantIdAndSlug("tenant1", "gX");
        assertThat(out).isEmpty();
    }
}
