package uao.edu.co.scouts_project.organigrama.repository;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.boot.autoconfigure.ImportAutoConfiguration;
import org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import uao.edu.co.scouts_project.organigrama.model.Section;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@ActiveProfiles("test")
@DataJpaTest(properties = "spring.jpa.hibernate.ddl-auto=none")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
// 1) Desactiva el auto-config por defecto de repos en esta clase de test
@ImportAutoConfiguration(exclude = JpaRepositoriesAutoConfiguration.class)
// 2) Importa la config que solo registra SectionRepository + entidades de organigrama
@Import(SectionRepositoryTest.JpaSliceConfig.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class SectionRepositoryTest {

    @Configuration
    @EnableJpaRepositories(basePackageClasses = SectionRepository.class)
    @EntityScan(basePackageClasses = Section.class)
    static class JpaSliceConfig { }

    @Autowired
    private SectionRepository sectionRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeAll
    void createSchema() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS section");
        jdbcTemplate.execute("""
            CREATE TABLE section (
                section_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id VARCHAR(255) NOT NULL,
                group_id BIGINT NOT NULL,
                name VARCHAR(255) NOT NULL,
                description VARCHAR(1024),
                icon_object_id UUID,
                photo_principal UUID,
                gallery_object_id UUID ARRAY,
                created_at TIMESTAMP,
                updated_at TIMESTAMP
            )
        """);
    }

    @BeforeEach
    void cleanTable() {
        jdbcTemplate.execute("DELETE FROM section");
    }

    private Section make(String tenantId, Long groupId, String name) {
        Section s = new Section(tenantId, groupId, name); // constructor usado en los tests del servicio
        s.setDescription("desc");
        s.setGalleryObjectIds(null);
        return s;
    }

    @Test
    @DisplayName("existsByGroupIdAndName → true cuando existe")
    void exists_trueWhenExists() {
        sectionRepository.save(make("tenant1", 1L, "Manada"));
        assertThat(sectionRepository.existsByGroupIdAndName(1L, "Manada")).isTrue();
    }

    @Test
    @DisplayName("existsByGroupIdAndName → false cuando no existe")
    void exists_falseWhenNotExists() {
        sectionRepository.save(make("tenant1", 1L, "Manada"));
        assertThat(sectionRepository.existsByGroupIdAndName(1L, "Tropa")).isFalse();
    }

    @Test
    @DisplayName("findByTenantIdAndGroupId → devuelve lista")
    void findByTenantAndGroup_returnsList() {
        sectionRepository.save(make("tenant1", 1L, "Manada"));
        sectionRepository.save(make("tenant1", 1L, "Tropa"));
        List<Section> out = sectionRepository.findByTenantIdAndGroupId("tenant1", 1L);
        assertThat(out).hasSize(2);
    }

    @Test
    @DisplayName("findByTenantIdAndGroupId → lista vacía si no hay datos")
    void findByTenantAndGroup_empty() {
        List<Section> out = sectionRepository.findByTenantIdAndGroupId("tenant1", 99L);
        assertThat(out).isEmpty();
    }

    @Test
    @DisplayName("findByTenantIdAndGroupIdAndSectionId → encuentra")
    void findByIds_found() {
        Section saved = sectionRepository.save(make("tenant1", 1L, "Manada"));
        Optional<Section> out = sectionRepository.findByTenantIdAndGroupIdAndSectionId("tenant1", 1L, saved.getSectionId());
        assertThat(out).isPresent();
        assertThat(out.get().getName()).isEqualTo("Manada");
    }

    @Test
    @DisplayName("findByTenantIdAndGroupIdAndSectionId → vacío si no coincide")
    void findByIds_empty() {
        Optional<Section> out = sectionRepository.findByTenantIdAndGroupIdAndSectionId("tenant1", 1L, 999L);
        assertThat(out).isEmpty();
    }
}
