package uao.edu.co.scouts_project.organigrama.repository;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.core.JdbcTemplate;

import uao.edu.co.scouts_project.organigrama.model.Subgroup;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = "spring.jpa.hibernate.ddl-auto=none")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class SubgroupRepositoryTest {

    @Configuration
    @EnableJpaRepositories(basePackageClasses = SubgroupRepository.class)
    @EntityScan(basePackageClasses = Subgroup.class)
    static class JpaSliceConfig { }

    @Autowired private SubgroupRepository subgroupRepository;
    @Autowired private JdbcTemplate jdbc;

    @BeforeAll
    void createSchema() {
        jdbc.execute("DROP TABLE IF EXISTS subgroup");
        jdbc.execute("""
            CREATE TABLE subgroup (
                subgroup_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id VARCHAR(255) NOT NULL,
                group_id BIGINT NOT NULL,
                section_id BIGINT NOT NULL,
                name VARCHAR(255) NOT NULL,
                description VARCHAR(2048),
                photo_principal UUID,
                is_active BOOLEAN NOT NULL,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            )
        """);
    }

    @BeforeEach
    void clean() { jdbc.execute("DELETE FROM subgroup"); }

    private Subgroup make(String tenantId, long groupId, long sectionId, String name) {
        Subgroup s = new Subgroup(tenantId, groupId, sectionId, name);
        s.setDescription(name + " desc");
        s.setIsActive(true);
        s.setCreatedAt(Instant.parse("2024-01-01T00:00:00Z"));
        s.setUpdatedAt(Instant.parse("2024-01-02T00:00:00Z"));
        return s;
    }

    @Test
    @DisplayName("existsBySectionIdAndName → true cuando existe en la sección")
    void exists_true() {
        subgroupRepository.save(make("T1", 42L, 100L, "Panteras"));
        boolean out = subgroupRepository.existsBySectionIdAndName(100L, "Panteras");
        assertThat(out).isTrue();
    }

    @Test
    @DisplayName("existsBySectionIdAndName → false cuando no coincide sección/nombre")
    void exists_false() {
        subgroupRepository.save(make("T1", 42L, 100L, "Panteras"));
        assertThat(subgroupRepository.existsBySectionIdAndName(100L, "Tigres")).isFalse();
        assertThat(subgroupRepository.existsBySectionIdAndName(101L, "Panteras")).isFalse();
    }

    @Test
    @DisplayName("findByTenantIdAndGroupIdAndSectionId → filtra por los 3 campos")
    void findByTenantGroupSection() {
        subgroupRepository.save(make("T1", 42L, 100L, "Panteras"));
        subgroupRepository.save(make("T1", 42L, 100L, "Tigres"));
        subgroupRepository.save(make("T1", 43L, 100L, "Lobos"));
        subgroupRepository.save(make("T2", 42L, 100L, "Halcones"));

        List<Subgroup> out = subgroupRepository.findByTenantIdAndGroupIdAndSectionId("T1", 42L, 100L);
        assertThat(out).extracting(Subgroup::getName).containsExactlyInAnyOrder("Panteras", "Tigres");
    }

    @Test
    @DisplayName("findById → encuentra por id")
    void findById_found() {
        Subgroup saved = subgroupRepository.save(make("T1", 42L, 100L, "Panteras"));
        Optional<Subgroup> out = subgroupRepository.findById(saved.getSubgroupId());
        assertThat(out).isPresent();
        assertThat(out.get().getName()).isEqualTo("Panteras");
    }

    @Test
    @DisplayName("delete → elimina registro")
    void delete_ok() {
        Subgroup saved = subgroupRepository.save(make("T1", 42L, 100L, "Panteras"));
        subgroupRepository.delete(saved);
        assertThat(subgroupRepository.findById(saved.getSubgroupId())).isEmpty();
    }
}
