CREATE TABLE Member (
    id_member BIGINT NOT NULL,
    identification BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150),
    gender VARCHAR(20),
    birth_date VARCHAR(20),
    city VARCHAR(100),
    address VARCHAR(150),
    phone BIGINT,
    institution VARCHAR(150),
    course VARCHAR(100),
    school_calendar VARCHAR(50),
    school_shift VARCHAR(50),
    weight DOUBLE,
    height DOUBLE,
    hobbies VARCHAR(255),
    sports VARCHAR(255),
    instruments VARCHAR(255),
    status VARCHAR(20),
    acceptance_date DATE,
    boss_id BIGINT,
    attendant_id BIGINT,
    CONSTRAINT pk_miembro PRIMARY KEY (id_miembro),
    CONSTRAINT fk_tenant FOREIGN KEY (tenant_id) REFERENCES Tenant(id_tenant),
    CONSTRAINT fk_subdivision FOREIGN KEY (subdi) REFERENCES Tenant(id_tenant),
    CONSTRAINT fk_boss FOREIGN KEY (boss_id) REFERENCES Member(identification),
    CONSTRAINT fk_attendant FOREIGN KEY (attendant_id) REFERENCES Member(identification),
    CONSTRAINT fk_subdivision FOREIGN KEY (subdivision_id) REFERENCES Subdivision(id_subdivision)
);
