CREATE TABLE Member (
    member_id BIGSERIAL PRIMARY KEY,
    subgroup_id BIGINT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    age INT,
    role VARCHAR(50) NOT NULL,
    identification BIGINT NOT NULL UNIQUE,
    document_type VARCHAR(50) NOT NULL,
    email VARCHAR(150),
    gender VARCHAR(20),
    birth_date DATE,
    address VARCHAR(150),
    phone VARCHAR(50),
    weight VARCHAR(50),
    height VARCHAR(50),
    hobbbies VARCHAR(255),
    sports VARCHAR(255),
    instruments VARCHAR(255),
    status VARCHAR(20),
    acceptance_date DATE,
    in_charge_of JSONB,
    emergency_phone JSON,
    updated_at TIMESTAMP,
    CONSTRAINT fk_subgroup FOREIGN KEY (subgroup_id) REFERENCES SubGroup(subgroup_id)
);
