import type { EstadoCuenta } from "@/types/estado-cuenta.type";

// DATOS MOCK PARA TESORERO (Vista Global)
// Members viene null porque el tesorero ve todas las cuotas del grupo
export const mockTesoreroData: EstadoCuenta = {
  kpis: {
    total_pendiente: 850000,
    total_pagado: 450000,
    cuotas_vencidas: 3, // Cuotas con status OVERDUE
  },
  members: null, // Para tesorero no hay members
  cuotas: [
    {
      installment_id: "inst-001",
      name: "Cuota Mensual Enero 2024",
      amount: 50000,
      due_date: new Date("2024-01-31"),
      status: "PAID",
      paid_at: new Date("2024-01-15"),
      method: "PSE",
      reference: "REF-001-PSE",
      payment_id: "pay-001",
      member_name: "Juan Pérez Gómez",
    },
    {
      installment_id: "inst-002",
      name: "Cuota Mensual Enero 2024",
      amount: 50000,
      due_date: new Date("2024-01-31"),
      status: "OVERDUE",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "María García López",
    },
    {
      installment_id: "inst-003",
      name: "Campamento de Verano",
      amount: 200000,
      due_date: new Date("2024-03-15"),
      status: "PENDING",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "Carlos Rodríguez Silva",
    },
    {
      installment_id: "inst-004",
      name: "Cuota Mensual Febrero 2024",
      amount: 50000,
      due_date: new Date("2024-02-28"),
      status: "PAID",
      paid_at: new Date("2024-02-10"),
      method: "Efectivo",
      reference: "REF-002-EFE",
      payment_id: "pay-002",
      member_name: "Ana Martínez Torres",
    },
    {
      installment_id: "inst-005",
      name: "Cuota Trimestral Q1 2024",
      amount: 150000,
      due_date: new Date("2024-03-31"),
      status: "PENDING",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "Pedro Sánchez Ruiz",
    },
    {
      installment_id: "inst-006",
      name: "Cuota Mensual Diciembre 2023",
      amount: 50000,
      due_date: new Date("2023-12-31"),
      status: "OVERDUE",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "Sofía Ramírez Díaz",
    },
    {
      installment_id: "inst-007",
      name: "Inscripción Anual 2024",
      amount: 100000,
      due_date: new Date("2024-01-15"),
      status: "PAID",
      paid_at: new Date("2024-01-05"),
      method: "Transferencia",
      reference: "REF-003-TRANS",
      payment_id: "pay-003",
      member_name: "Luis González Morales",
    },
    {
      installment_id: "inst-008",
      name: "Cuota Mensual Noviembre 2023",
      amount: 50000,
      due_date: new Date("2023-11-30"),
      status: "OVERDUE",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "Laura Fernández Castro",
    },
    {
      installment_id: "inst-009",
      name: "Material Didáctico",
      amount: 75000,
      due_date: new Date("2024-02-15"),
      status: "PAID",
      paid_at: new Date("2024-02-12"),
      method: "PSE",
      reference: "REF-004-PSE",
      payment_id: "pay-004",
      member_name: "Diego Jiménez Vargas",
    },
    {
      installment_id: "inst-010",
      name: "Cuota Mensual Febrero 2024",
      amount: 50000,
      due_date: new Date("2024-02-28"),
      status: "PENDING",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "Valentina Ortiz Mendoza",
    },
  ],
};

// DATOS MOCK PARA ACUDIENTE (Vista por hijo)
// Members viene lleno con la lista de hijos del acudiente
export const mockAcudienteData: EstadoCuenta = {
  kpis: {
    total_pendiente: 300000,
    total_pagado: 200000,
    cuotas_vencidas: 1, // Cuotas con status OVERDUE
  },
  members: [
    {
      member_id: "member-001",
      member_name: "Juan Pérez Gómez",
      age: 14,
      subgroup: {
        subgroup_id: "subg-001",
        name: "Tropa Halcones",
      },
      section: {
        section_id: "sect-001",
        name: "Tropa Scout",
      },
    },
    {
      member_id: "member-002",
      member_name: "María Pérez Gómez",
      age: 10,
      subgroup: {
        subgroup_id: "subg-002",
        name: "Manada Lobos",
      },
      section: {
        section_id: "sect-002",
        name: "Manada",
      },
    },
    {
      member_id: "member-003",
      member_name: "Carlos Pérez Gómez",
      age: 17,
      subgroup: {
        subgroup_id: "subg-003",
        name: "Clan Aventureros",
      },
      section: {
        section_id: "sect-003",
        name: "Clan Rover",
      },
    },
  ],
  cuotas: [
    // Cuotas de Juan
    {
      installment_id: "inst-101",
      name: "Cuota Mensual Enero 2024",
      amount: 50000,
      due_date: new Date("2024-01-31"),
      status: "PAID",
      paid_at: new Date("2024-01-15"),
      method: "PSE",
      reference: "REF-101-PSE",
      payment_id: "pay-101",
      member_name: "Juan Pérez Gómez",
    },
    {
      installment_id: "inst-102",
      name: "Cuota Mensual Febrero 2024",
      amount: 50000,
      due_date: new Date("2024-02-28"),
      status: "PENDING",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "Juan Pérez Gómez",
    },
    {
      installment_id: "inst-103",
      name: "Campamento de Verano",
      amount: 200000,
      due_date: new Date("2024-03-15"),
      status: "PENDING",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "Juan Pérez Gómez",
    },
    // Cuotas de María
    {
      installment_id: "inst-201",
      name: "Cuota Mensual Enero 2024",
      amount: 50000,
      due_date: new Date("2024-01-31"),
      status: "PAID",
      paid_at: new Date("2024-01-20"),
      method: "Efectivo",
      reference: "REF-201-EFE",
      payment_id: "pay-201",
      member_name: "María Pérez Gómez",
    },
    {
      installment_id: "inst-202",
      name: "Cuota Mensual Febrero 2024",
      amount: 50000,
      due_date: new Date("2024-02-28"),
      status: "PAID",
      paid_at: new Date("2024-02-18"),
      method: "PSE",
      reference: "REF-202-PSE",
      payment_id: "pay-202",
      member_name: "María Pérez Gómez",
    },
    // Cuotas de Carlos
    {
      installment_id: "inst-301",
      name: "Cuota Mensual Diciembre 2023",
      amount: 50000,
      due_date: new Date("2023-12-31"),
      status: "OVERDUE",
      paid_at: null,
      method: null,
      reference: null,
      payment_id: null,
      member_name: "Carlos Pérez Gómez",
    },
  ],
};