spring.application.name=scouts-project

# ==== Perfil activo ====
spring.profiles.active=${SPRING_PROFILES_ACTIVE:development}

# ==== Hibernate ====
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==== Auth0 / Okta ====
okta.oauth2.issuer=https://dev-peshzy4g14jvfyku.us.auth0.com/
okta.oauth2.audience=https://scouts-platform-backend/
auth0.domain=dev-peshzy4g14jvfyku.us.auth0.com
auth0.audience=https://dev-peshzy4g14jvfyku.us.auth0.com/api/v2/
auth0.management.eager-init=true
auth0.management.background-refresh.enabled=true
auth0.management.refresh-check-interval=300000
authz.cache.ttl-millis=300000

# ==== Supabase Storage ====
SUPABASE_STORAGE_FOLDER=organigrama
SUPABASE_STORAGE_SIGN_TTL=3600

# ==== Liquibase / Hibernate ====
spring.liquibase.enabled=false

# ====== TEST DEPLOY ======
# ==== Supabase ====
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require\
&preferQueryMode=simple\
&reWriteBatchedInserts=true\
&ApplicationName=scouts-backend

spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=200000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-test-query=SELECT 1

# Evita transacciones largas abiertas por vistas
spring.jpa.open-in-view=false

spring.datasource.hikari.data-source-properties.sslmode=require
supabase.service.role.key=${SUPABASE_SERVICE_ROLE_KEY:test}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}
supabase.images.bucket=images
supabase.url=https://mirhzylkikwpydtwelvj.supabase.co
spring.datasource.driver-class-name=org.postgresql.Driver

# ==== Auth0 =====
auth0.clientSecret=${AUTH0_CLIENT_SECRET}
auth0.clientId=${AUTH0_CLIENT_ID}

# ==== Hibernate ====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# ==== Server ====
server.port=8080

# ==== Logging ====
debug=false
logging.level.uao.edu.co.scouts_project=info
logging.level.org.springframework.security=info
logging.level.org.springframework.boot.context.config=DEBUG