spring.application.name=scouts-project

# ==== Perfil activo ====
spring.profiles.active=${SPRING_PROFILES_ACTIVE:production}

# ==== Hibernate ==== 
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==== Auth0 / Okta ====
okta.oauth2.issuer=https://dev-peshzy4g14jvfyku.us.auth0.com/
okta.oauth2.audience=https://scouts-platform-backend/
auth0.domain=dev-peshzy4g14jvfyku.us.auth0.com
auth0.audience=https://dev-peshzy4g14jvfyku.us.auth0.com/api/v2/
auth0.management.eager-init=true
auth0.management.background-refresh.enabled=true
auth0.management.refresh-check-interval=300000
authz.cache.ttl-millis=300000

# ==== Supabase Storage ====
SUPABASE_STORAGE_FOLDER=organigrama
SUPABASE_STORAGE_SIGN_TTL=3600

# ==== Liquibase / Hibernate ====
spring.liquibase.enabled=false

# ====== TEST DEPLOY ======
# ==== Supabase ====
spring.datasource.url=jdbc:postgresql://db.xjkbcpqkvcxbsnffgobp.supabase.co:5432/postgres?sslmode=require\
&preferQueryMode=simple\
&reWriteBatchedInserts=true\
&ApplicationName=scouts-backend

spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=2

# Vida Ã¯Â¿Â½til de conexiones (recicla antes de que el server/pooler las mate)
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.keepalive-time=60000

# Handshake/checkout
spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=0

spring.datasource.hikari.connection-test-query=SELECT 1
spring.jpa.open-in-view=false
spring.datasource.hikari.data-source-properties.sslmode=require
supabase.service.role.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pcmh6eWxraWt3cHlkdHdlbHZqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1ODg2NjE4NSwiZXhwIjoyMDc0NDQyMTg1fQ.oEFqC2sA7X9IL6jSM_UOFaWAWXEIZXIx9QnpRSCZ1AA
spring.datasource.username=app_user
spring.datasource.password=app_user
supabase.images.bucket=images
supabase.url=https://mirhzylkikwpydtwelvj.supabase.co
spring.datasource.driver-class-name=org.postgresql.Driver

# ==== Auth0 =====
auth0.clientSecret=SVzNAKpa5iQ9O6Fom9GVLp-n3hXQPmEOxA5RCj-i3DXIB6ceFa5iSGifcKMNsGpP
auth0.clientId=OiWaUylWieF26UdxNdISP7LtZiIwANR8
AUTH0_CONNECTIONS_ENABLED_CLIENTS=E1fqntn0ryTTylXazK30a5EpJjzmIg7f,OiWaUylWieF26UdxNdISP7LtZiIwANR8

# ==== Server ====
server.port=8080

# ==== Logging ====
debug=true
logging.level.uao.edu.co.scouts_project=info
logging.level.org.springframework.security=info
logging.level.org.springframework.boot.context.config= info