-- Creates the `auth0_roles` table.
-- id: text primary key with autogenerated UUID stored as text

CREATE TABLE IF NOT EXISTS auth0_roles (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	auth0_rol text NOT NULL,
	nombre text NOT NULL
);