create table if not exists "Miembro" (
    id_miembro integer primary key,
    identificacion bigint not null,
    tipoDocumento text not null,
    nombres text not null,
    apellidos text not null,
    correo text,
    sexo text,
    fechaNacimiento text,
    ciudad text,
    direccion text,
    telefono bigint,
    institucion text,
    curso text,
    calendarioEscolar text,
    jornadaEscolar text,
    peso double precision,
    estatura double precision,
    tipoSangre text,
    factorRh text,
    pasatiempos text,
    deportes text,
    instrumentos text,
    estado text check (estado in ('ACTIVO','INACTIVO','SUSPENDIDO')), -- según tu Enum
    fechaAceptacion date
);
