-- Creates the `auth0_roles` table

BEGIN;

CREATE TABLE IF NOT EXISTS auth0_roles (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	auth0_rol text NOT NULL,
	nombre text NOT NULL,
    -- Ensure auth0_rol is unique
	CONSTRAINT uq_auth0_roles_auth0_rol UNIQUE (auth0_rol)
);

COMMIT;