-- User and Role Creations
CREATE USER reader WITH PASSWORD 'placeHolder' LOGIN;
CREATE USER api_user WITH PASSWORD 'placeHolder' LOGIN;
CREATE USER dba WITH PASSWORD '${DBA_PASSWORD}' LOGIN;

-- dba rls bypass
ALTER USER dba WITH BYPASSRLS;

-- Grants for dba
GRANT USAGE ON SCHEMA public TO dba;
GRANT CREATE ON SCHEMA public TO dba;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO dba;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO dba;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO dba;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA public TO dba;

-- Default Privileges for dba
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO dba;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO dba;

-- Grants for reader
GRANT SELECT ON ALL TABLES IN SCHEMA public TO reader;

-- Default Privileges for reader
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO reader;

-- Grants for api_user
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO api_user;

-- Default Privileges for api_user
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api_user;

-- Grants for authenticated
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO authenticated;
