-- fix for dba role
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "dba";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "dba";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "dba";

ALTER USER dba WITH BYPASSRLS;
GRANT USAGE ON SCHEMA public TO dba;
GRANT CREATE ON SCHEMA public TO dba;
